import React, { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { exportReport } from "../../../services/reportService";
import "./ExportReport.css";

export default function ExportReport() {
  const { id: paramId } = useParams();
  const navigate = useNavigate();

  const [reportId, setReportId] = useState(paramId || "");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);

  const handleExportSubmit = async (e) => {
    e.preventDefault();
    if (!reportId.trim()) {
      setError("Please enter a valid Report ID.");
      return;
    }

    setLoading(true);
    setError(null);
    setSuccess(false);

    try {
      await exportReport(reportId.trim());
      setSuccess(true);
    } catch (err) {
      setError(err.message || "Failed to download CSV export");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="export-report-page">
      <div className="page-card">
        <div className="page-card-header">
          <h2>Export Report CSV</h2>
          <p>Download official comma-separated values (CSV) payroll data generated by backend service.</p>
        </div>

        <form className="export-form" onSubmit={handleExportSubmit}>
          <div className="form-group">
            <label htmlFor="reportId">Report Mongo ID</label>
            <input
              id="reportId"
              type="text"
              placeholder="e.g. 64f1a2b3c4d5e6f7a8b9c0d1"
              value={reportId}
              onChange={(e) => setReportId(e.target.value)}
            />
          </div>

          <div className="export-actions-row">
            <button type="submit" className="btn-primary" disabled={loading}>
              {loading ? "Downloading CSV..." : "Download CSV Report"}
            </button>
            <button type="button" className="btn-secondary" onClick={() => navigate("/reports/dashboard")}>
              Back to Dashboard
            </button>
          </div>
        </form>

        {error && <div className="report-alert alert-error">{error}</div>}

        {success && (
          <div className="report-alert alert-success">
            Report CSV file generated and downloaded successfully!
          </div>
        )}
      </div>
    </div>
  );
}
